name:                pubsEngine
version:             0.1.0.1
github:              "hasanalrasyid/pubsEngine"
license:             BSD3
author:              "Hasan al Rasyid"
maintainer:          "hasanalrasyid.har@gmail.com"
copyright:           "2021 Hasan al Rasyid"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hasanalrasyid/pubsEngine#readme>

dependencies:
- base >= 4.7 && < 5
- text
- pandoc-types
- filepath
- directory
- pandoc
- process
# diagrams-pgf        # library
# diagrams
# diagrams-lib
# diagrams-builder
- bytestring
- containers # pandoc-crossref
# utility-ht
- data-default
- mtl
# data-accessor
# data-accessor-transformers
# data-accessor-template
# syb
# roman-numerals
# template-haskell
# haskell-src-exts-simple
# random
# aeson
# cryptonite
- raw-strings-qq
# Diagrams
- linear
#     monoid-extras
- groups
- semigroupoids
# diagrams-core
- profunctors
- unordered-containers
- distributive
- adjunctions
- optparse-applicative
#   dual-tree
- newtype-generics
# diagrams-lib
- intervals
- diagrams-solve
- data-default-class
- colour
- cereal
- fingertree
- array
- fsnotify
# Diagrams Backend: PGF
- hashable
- zlib
- JuicyPixels
- vector
#     Monoid Extras
- QuickCheck
#     Texrunner
- attoparsec
- temporary
- io-streams
# Diagrams Builder
- cmdargs
- lens
- haskell-src-exts
- exceptions
- transformers
- split
- base-orphans
- hint

library:
  source-dirs:
    - src
    - extern/monoid-extras/src
    - extern/dual-tree/src
    - extern/active/src
    - extern/diagrams-core/src
    - extern/diagrams-lib/src
    - extern/diagrams-pgf/src
    - extern/texrunner/src
    - extern/diagrams-builder/src
    - extern/haskell-src-exts-simple/src
  default-extensions: OverloadedStrings
                    , GeneralizedNewtypeDeriving
                    , ScopedTypeVariables
                    , RecordWildCards
                    , DeriveDataTypeable
                    , GADTs
                    , FlexibleContexts
                    , StandaloneDeriving

executables:
  pubsEngine:
    main:                pubs.hs
    source-dirs:
      - app
      - templates
    dependencies:
      - pandoc
      - pandoc-crossref
      - file-embed
      - pubsEngine
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2

# thesis:
#   main:                thesis.hs
#   source-dirs:         app
#   dependencies:
#     - pubsEngine
#   ghc-options:
#   - -threaded
#   - -rtsopts
#   - -with-rtsopts=-N
#   - -O2

tests:
  pubsEngine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pubsEngine
